#!/usr/bin/env bash
# Build a *local* Home Assistant add-on from this working tree.
#
# The published add-on clones its source from GitHub at build time, which is
# the right thing for an installed add-on and the wrong thing while you are
# still changing the code. This script vendors the current checkout into a
# self-contained add-on directory you copy to Home Assistant's /addons share;
# the Supervisor then builds exactly what you have, with no push required.
#
# Usage:
#   ha-addon/prepare-local-addon.sh [output-dir]
#
# Then copy the result to your Home Assistant machine:
#   scp -r <output-dir> root@homeassistant:/addons/bambuddy
# and look for "Bambuddy (local)" under Settings → Add-ons → Add-on Store →
# Local add-ons (use the store's ⋮ → "Check for updates" if it is not listed).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-${repo_root}/build/ha-addon-local}"

echo "Repository: ${repo_root}"
echo "Output:     ${out}"

rm -rf "${out}"
mkdir -p "${out}/app"

cp "${repo_root}/ha-addon/bambuddy/config.yaml" "${out}/config.yaml"
cp "${repo_root}/ha-addon/bambuddy/run.sh" "${out}/run.sh"
cp "${repo_root}/ha-addon/bambuddy/DOCS.md" "${out}/DOCS.md"
chmod +x "${out}/run.sh"

# A local add-on needs its own slug and name, or it collides with the one
# installed from the repository and the store shows two identical entries.
sed -i.bak -e 's/^slug: bambuddy$/slug: bambuddy_local/' \
           -e 's/^name: Bambuddy$/name: Bambuddy (local)/' "${out}/config.yaml"
rm -f "${out}/config.yaml.bak"

# Only what the image needs. Notably not .git (hundreds of megabytes of
# history the build would copy and then discard) and not node_modules.
for path in backend frontend slicer-api requirements.txt; do
    cp -R "${repo_root}/${path}" "${out}/app/${path}"
done
rm -rf "${out}/app/frontend/node_modules" "${out}/app/frontend/dist"
find "${out}/app" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

# A build context that copies its source instead of cloning it. Kept separate
# from ha-addon/bambuddy/Dockerfile rather than parameterised: the two differ
# in where the source comes from and nothing else, and a single Dockerfile
# with a conditional clone would be harder to read than two honest ones.
cat > "${out}/Dockerfile" <<'DOCKERFILE'
# Local Bambuddy add-on — builds the vendored working tree in ./app.
# Generated by ha-addon/prepare-local-addon.sh; edit that, not this.
FROM node:22-bookworm-slim AS frontend-builder
WORKDIR /src
COPY app/frontend /src/frontend
WORKDIR /src/frontend
RUN npm ci && npm run build

FROM python:3.13-slim-trixie
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl ffmpeg ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY app/requirements.txt /app/requirements.txt
RUN pip install --root-user-action=ignore --upgrade 'pip>=26.1.2' \
    && pip install --root-user-action=ignore -r /app/requirements.txt
COPY app/backend /app/backend
COPY app/slicer-api /app/slicer-api
COPY --from=frontend-builder /src/static /app/static
COPY run.sh /run.sh
RUN chmod +x /run.sh
ENV DATA_DIR=/data \
    PYTHONUNBUFFERED=1 \
    MPLCONFIGDIR=/tmp/matplotlib \
    UVICORN_TIMEOUT_GRACEFUL_SHUTDOWN=5
CMD ["/run.sh"]
DOCKERFILE

echo
echo "Done. Copy ${out} to /addons/bambuddy on your Home Assistant machine."
